#!/usr/bin/env bash
#
# Run all dotfiles installers.

set -e

cd "$(dirname $0)"/..

# Install packages
echo "› apt install"
sudo apt install $(grep -vE "^\s*#" apt-files  | tr "\n" " ")


# find the installers and run them iteratively
find . -name install.sh | while read installer ; do sh -c "${installer}" ; done
